name: CD

on: [push]

jobs:
  build:

    name: surge.sh deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - run: npm ci --production
    - run: npm run build
    - run: npx surge ./public/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}